version: "3.7"
services:
  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mynet
    ports:
      - 27017:27017
  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    environment:
      DB_HOST: mongo
    networks:
      - mynet
    ports:
    - "8080:8080"
networks:
  mynet:
    driver: bridge